export const slides = [
  {
    image: "/images/hero-architecture.jpg",
    title: "Obra International Ltd",
    text: "Quantity surveyors, project managers and arbitrators. We sit down first, count the cost, and stay with the work until it is finished.",
  },
  {
    image: "/images/hero-villa.jpg",
    title: "Luke 14:28",
    text: "For which of you, intending to build a tower, does not sit down first and count the cost, whether he has enough to finish it.",
  },
  {
    image: "/images/hero-plans.jpg",
    title: "Cost, contract, delivery",
    text: "Housing, infrastructure, institutions and industry. One practice for the figure, the form of contract, and the finish.",
  },
]

export const services = [
  {
    icon: "/images/illu-qs.svg",
    title: "Quantity Surveying Services",
    summary:
      "Feasibility studies and development budgets. Cash-flow projections. Cost planning, control and estimates. Bills of quantities, tendering and final accounts.",
    points: [
      "Feasibility studies and developers’ budgets",
      "Cash-flow projections across the build",
      "Cost planning, cost control and budget estimates",
      "Bills of quantities and specifications",
      "Tendering procedures and tender reports",
      "Valuations, variations and final accounts",
    ],
  },
  {
    icon: "/images/illu-pm.svg",
    title: "Project Management",
    summary:
      "Briefs, programmes and consultant coordination. Procurement strategy, progress and cost reporting, and a controlled handover.",
    points: [
      "Site and brief confirmation with the employer",
      "Feasibility studies and reports",
      "Advice on project finance and procurement strategy",
      "Recommendation of consultant appointments",
      "Programme, cost and quality reporting through construction",
      "Handover, defects and close-out",
    ],
  },
  {
    icon: "/images/illu-arb.svg",
    title: "Arbitration",
    summary:
      "Quantum analysis, expert evidence, and contract advice on FIDIC, NEC and JCT. Claims prepared so a tribunal can follow the money.",
    points: [
      "Quantum analysis of claims, disruption and prolongation",
      "Expert evidence of fact for employers and contractors",
      "Contract advice on FIDIC, NEC and JCT",
      "Preparation of statements of claim and responses",
      "Advisory work before a dispute hardens into a reference",
    ],
  },
  {
    icon: "/images/illu-audit.svg",
    title: "Forensic and Project Audit",
    summary: "",
    points: [
      "Independent review of cost, programme and payments",
      "Tracing of variations, provisional sums and contingencies",
      "Reports written for boards, funders and employers",
    ],
  },
  {
    icon: "/images/illu-claims.svg",
    title: "Quantum and Claims",
    summary: "",
    points: [
      "Build-up of measured loss, expense and prolongation",
      "Contract documents shaped to the funding model: EPC, PPP, government and donor-funded work",
      "Value engineering that still leaves a building that can be finished",
    ],
  },
  {
    icon: "/images/illu-verify.svg",
    title: "Project Verification",
    summary: "",
    points: [
      "Checking that what was measured is what was built",
      "Support to certification and value-for-money reviews",
      "A clear record for the employer, the funder and the contractor",
    ],
  },
]

export const filters = [
  { id: "residential", label: "Residential Properties" },
  { id: "public", label: "Public-State Institutions" },
  { id: "religious", label: "Religious Institutions" },
  { id: "market", label: "Market Complex" },
]

export const projects = [
  {
    id: "res-01",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/01.jpg",
    alt: "Residential property",
  },
  {
    id: "res-02",
    cat: "residential",
    title: "Levert Apartments",
    place: "Riverside, Nairobi",
    image: "/images/residential/02-levert.jpg",
    alt: "Levert Apartments, Riverside, Nairobi",
    featured: true,
  },
  {
    id: "res-03",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/03.jpg",
    alt: "Residential property",
  },
  {
    id: "res-04",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/04.jpg",
    alt: "Residential property",
  },
  {
    id: "res-05",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/05.jpg",
    alt: "Residential property",
  },
  {
    id: "res-06",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/06.jpg",
    alt: "Residential property",
  },
  {
    id: "res-07",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/07.jpg",
    alt: "Residential property",
  },
  {
    id: "res-08",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/08.jpg",
    alt: "Residential property",
  },
  {
    id: "res-09",
    cat: "residential",
    title: "Brookview Estate",
    place: "Membley, Kiambu",
    image: "/images/residential/09-brookview.jpg",
    alt: "Brookview Estate, Membley, Kiambu",
    featured: true,
  },
  {
    id: "res-10",
    cat: "residential",
    title: "Amara Ridge",
    place: "Karen, Nairobi",
    image: "/images/residential/10-amara.jpg",
    alt: "Amara Ridge, Karen, Nairobi",
    featured: true,
  },
  {
    id: "res-11",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/11.jpg",
    alt: "Residential property",
  },
  {
    id: "res-12",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/12.jpg",
    alt: "Residential property",
  },
  {
    id: "res-13",
    cat: "residential",
    title: "Kasarani Affordable Housing Project",
    place: "Kasarani, Nairobi",
    image: "/images/residential/13-kasarani.jpg",
    alt: "Kasarani Affordable Housing Project, Kasarani, Nairobi",
    featured: true,
  },
  {
    id: "res-14",
    cat: "residential",
    title: "Ophelia Apartments",
    place: "Kilimani, Nairobi",
    image: "/images/residential/14-ophelia.jpg",
    alt: "Ophelia Apartments, Kilimani, Nairobi",
    featured: true,
  },
  {
    id: "res-15",
    cat: "residential",
    title: "",
    place: "",
    image: "/images/residential/15.jpg",
    alt: "Residential property",
  },
  {
    id: "pub-01",
    cat: "public",
    title: "Nakuru County Assembly",
    place: "Nakuru Town, Nakuru",
    image: "/images/public/01-nakuru.jpg",
    alt: "Nakuru County Assembly, Nakuru Town, Nakuru",
    featured: true,
  },
  {
    id: "pub-02",
    cat: "public",
    title: "Kenya Civil Aviation Authority (KCAA)",
    place: "Air Control & Disaster Recovery Center, Mlolongo, Nairobi",
    image: "/images/public/02-kcaa.jpg",
    alt: "Kenya Civil Aviation Authority, Air Control and Disaster Recovery Center, Mlolongo, Nairobi",
    featured: true,
  },
  {
    id: "pub-03",
    cat: "public",
    title: "",
    place: "",
    image: "/images/public/03.jpg",
    alt: "Public-state institution",
  },
  {
    id: "pub-04",
    cat: "public",
    title: "West Pokot County Assembly",
    place: "Kapenguria, West Pokot",
    image: "/images/public/04-west-pokot.jpg",
    alt: "West Pokot County Assembly, Kapenguria, West Pokot",
    featured: true,
  },
  {
    id: "mkt-01",
    cat: "market",
    title: "Kimanas ESP Market",
    place: "Kimana, Kajiado",
    image: "/images/market/01-kimanas.jpg",
    alt: "Kimanas ESP Market, Kimana, Kajiado",
    featured: true,
  },
  {
    id: "mkt-02",
    cat: "market",
    title: "",
    place: "",
    image: "/images/market/02.jpg",
    alt: "Market complex",
  },
  {
    id: "mkt-03",
    cat: "market",
    title: "Embu ESP Market",
    place: "Makutano, Embu",
    image: "/images/market/03-embu.jpg",
    alt: "Embu ESP Market, Makutano, Embu",
    featured: true,
  },
  {
    id: "mkt-04",
    cat: "market",
    title: "",
    place: "",
    image: "/images/market/04.jpg",
    alt: "Market complex",
  },
  {
    id: "rel-01",
    cat: "religious",
    title: "St. Veronica Catholic Church",
    place: "Syokimau, Nairobi",
    image: "/images/religious/01-st-veronica.jpg",
    alt: "St. Veronica Catholic Church, Syokimau, Nairobi",
    featured: true,
  },
]

const categoryLabel = {
  residential: "Residential Properties",
  public: "Public-State Institutions",
  religious: "Religious Institutions",
  market: "Market Complex",
}

export const stories = projects
  .filter((item) => item.featured)
  .map((item) => ({
    image: item.image,
    alt: item.alt,
    kicker: `${categoryLabel[item.cat]} · ${item.place}`,
    title: item.title,
    text: item.place,
  }))

export const gallery = projects.map((item) => [
  item.image,
  item.title || "",
  [item.title, item.place].filter(Boolean).join(", ") || categoryLabel[item.cat],
])
